namespace: production
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: nginx-deployment
    patch: |-
      - op: replace 
        path: /spec/replicas
        value: 4
patchesStrategicMerge:
  - patch-deployment.yaml